
import { Youth } from "@/types/app-types";

export const mockYouthData: Omit<Youth, 'id'>[] = [
  {
    firstName: "Michael",
    lastName: "Johnson",
    age: 16,
    dob: new Date("2008-03-15"),
    admissionDate: new Date("2024-01-15"),
    level: 2,
    pointTotal: 145000,
    referralSource: "County Social Services",
    referralReason: "Family conflict and truancy issues",
    legalStatus: "Court ordered placement",
    educationInfo: "Currently in 10th grade, struggles with math",
    medicalInfo: "No known allergies, regular checkups",
    mentalHealthInfo: "Diagnosed with ADHD, taking medication",
    peerInteraction: 4,
    adultInteraction: 3,
    investmentLevel: 4,
    dealAuthority: 2,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 65,
    hyrnaAssessmentDate: new Date("2024-01-20"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    firstName: "David",
    lastName: "Williams",
    age: 15,
    dob: new Date("2009-07-22"),
    admissionDate: new Date("2024-02-01"),
    level: 1,
    pointTotal: 89000,
    referralSource: "Department of Children Services",
    referralReason: "Behavioral issues at home and school",
    legalStatus: "Voluntary placement",
    educationInfo: "9th grade, good in English and history",
    medicalInfo: "Asthma, uses inhaler as needed",
    mentalHealthInfo: "Anxiety disorder, seeing counselor weekly",
    peerInteraction: 2,
    adultInteraction: 3,
    investmentLevel: 2,
    dealAuthority: 1,
    hyrnaRiskLevel: "Low",
    hyrnaScore: 35,
    hyrnaAssessmentDate: new Date("2024-02-05"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01")
  },
  {
    firstName: "James",
    lastName: "Brown",
    age: 17,
    dob: new Date("2007-11-08"),
    admissionDate: new Date("2024-01-10"),
    level: 3,
    pointTotal: 234000,
    referralSource: "Juvenile Court",
    referralReason: "Probation violation and substance abuse",
    legalStatus: "Court ordered residential treatment",
    educationInfo: "11th grade, working toward GED",
    medicalInfo: "Previous sports injury, left knee",
    mentalHealthInfo: "Substance abuse counseling, group therapy",
    peerInteraction: 5,
    adultInteraction: 4,
    investmentLevel: 5,
    dealAuthority: 4,
    hyrnaRiskLevel: "High",
    hyrnaScore: 85,
    hyrnaAssessmentDate: new Date("2024-01-15"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10")
  },
  {
    firstName: "Christopher",
    lastName: "Davis",
    age: 14,
    dob: new Date("2010-05-30"),
    admissionDate: new Date("2024-03-01"),
    level: 1,
    pointTotal: 56000,
    referralSource: "School District",
    referralReason: "Chronic absenteeism and behavioral problems",
    legalStatus: "Educational placement",
    educationInfo: "8th grade, strong in science",
    medicalInfo: "Type 1 diabetes, insulin dependent",
    mentalHealthInfo: "Depression, individual therapy sessions",
    peerInteraction: 1,
    adultInteraction: 2,
    investmentLevel: 1,
    dealAuthority: 1,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 55,
    hyrnaAssessmentDate: new Date("2024-03-05"),
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01")
  },
  {
    firstName: "Eloy",
    lastName: "Martinez",
    age: 15,
    dob: new Date("2009-08-12"),
    admissionDate: new Date("2024-05-10"),
    level: 2,
    pointTotal: 132000,
    referralSource: "Family Court",
    referralReason: "Anger management and school behavioral issues",
    legalStatus: "Court ordered placement",
    educationInfo: "9th grade, excels in math but struggles with English",
    medicalInfo: "No known medical issues",
    mentalHealthInfo: "Anger management therapy, weekly sessions",
    peerInteraction: 3,
    adultInteraction: 2,
    investmentLevel: 3,
    dealAuthority: 2,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 58,
    hyrnaAssessmentDate: new Date("2024-05-15"),
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-10")
  },
  {
    firstName: "Chance",
    lastName: "Wilson",
    age: 16,
    dob: new Date("2008-11-23"),
    admissionDate: new Date("2024-04-18"),
    level: 3,
    pointTotal: 185000,
    referralSource: "Juvenile Probation",
    referralReason: "Substance abuse and truancy",
    legalStatus: "Probation requirement",
    educationInfo: "10th grade, good at creative writing",
    medicalInfo: "Mild asthma, uses inhaler occasionally",
    mentalHealthInfo: "Substance abuse counseling, shows good progress",
    peerInteraction: 4,
    adultInteraction: 3,
    investmentLevel: 4,
    dealAuthority: 3,
    hyrnaRiskLevel: "Medium-High",
    hyrnaScore: 72,
    hyrnaAssessmentDate: new Date("2024-04-25"),
    createdAt: new Date("2024-04-18"),
    updatedAt: new Date("2024-04-18")
  },
  {
    firstName: "Peyton",
    lastName: "Anderson",
    age: 14,
    dob: new Date("2010-09-30"),
    admissionDate: new Date("2024-06-05"),
    level: 1,
    pointTotal: 78000,
    referralSource: "School District",
    referralReason: "Bullying incidents and poor academic performance",
    legalStatus: "Voluntary placement",
    educationInfo: "8th grade, struggles with all subjects",
    medicalInfo: "ADHD medication",
    mentalHealthInfo: "Individual therapy for anger and impulse control",
    peerInteraction: 2,
    adultInteraction: 3,
    investmentLevel: 2,
    dealAuthority: 1,
    hyrnaRiskLevel: "Low-Medium",
    hyrnaScore: 45,
    hyrnaAssessmentDate: new Date("2024-06-10"),
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-05")
  },
  {
    firstName: "Elijah",
    lastName: "Thomas",
    age: 17,
    dob: new Date("2007-07-15"),
    admissionDate: new Date("2024-02-28"),
    level: 4,
    pointTotal: 275000,
    referralSource: "Juvenile Court",
    referralReason: "Repeated probation violations",
    legalStatus: "Court mandated treatment",
    educationInfo: "11th grade, strong in sciences and math",
    medicalInfo: "No significant medical issues",
    mentalHealthInfo: "Behavioral therapy, shows excellent progress",
    peerInteraction: 5,
    adultInteraction: 4,
    investmentLevel: 5,
    dealAuthority: 4,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 60,
    hyrnaAssessmentDate: new Date("2024-03-10"),
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-02-28")
  },
  {
    firstName: "Emiliano",
    lastName: "Garcia",
    age: 15,
    dob: new Date("2009-05-18"),
    admissionDate: new Date("2024-03-20"),
    level: 2,
    pointTotal: 125000,
    referralSource: "Family Services",
    referralReason: "Family conflict and runaway episodes",
    legalStatus: "Temporary custody",
    educationInfo: "9th grade, bilingual (English/Spanish), good verbal skills",
    medicalInfo: "Seasonal allergies",
    mentalHealthInfo: "Family therapy sessions weekly",
    peerInteraction: 4,
    adultInteraction: 3,
    investmentLevel: 3,
    dealAuthority: 2,
    hyrnaRiskLevel: "Low",
    hyrnaScore: 38,
    hyrnaAssessmentDate: new Date("2024-03-25"),
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20")
  },
  {
    firstName: "Jaden",
    lastName: "Harris",
    age: 16,
    dob: new Date("2008-12-07"),
    admissionDate: new Date("2024-04-02"),
    level: 2,
    pointTotal: 156000,
    referralSource: "Child Protective Services",
    referralReason: "Neglect situation and behavioral concerns",
    legalStatus: "State custody",
    educationInfo: "10th grade, interest in music and arts",
    medicalInfo: "Needs regular dental care",
    mentalHealthInfo: "Trauma-focused therapy, moderate progress",
    peerInteraction: 3,
    adultInteraction: 2,
    investmentLevel: 4,
    dealAuthority: 3,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 52,
    hyrnaAssessmentDate: new Date("2024-04-10"),
    createdAt: new Date("2024-04-02"),
    updatedAt: new Date("2024-04-02")
  },
  {
    firstName: "Curtis",
    lastName: "Robinson",
    age: 15,
    dob: new Date("2009-10-14"),
    admissionDate: new Date("2024-05-22"),
    level: 1,
    pointTotal: 95000,
    referralSource: "Juvenile Probation",
    referralReason: "Property damage and truancy",
    legalStatus: "Probation requirement",
    educationInfo: "9th grade, skilled in technical subjects",
    medicalInfo: "Mild vision impairment, wears glasses",
    mentalHealthInfo: "Group therapy for impulse control",
    peerInteraction: 2,
    adultInteraction: 3,
    investmentLevel: 2,
    dealAuthority: 2,
    hyrnaRiskLevel: "Medium",
    hyrnaScore: 62,
    hyrnaAssessmentDate: new Date("2024-05-25"),
    createdAt: new Date("2024-05-22"),
    updatedAt: new Date("2024-05-22")
  },
  {
    firstName: "Jason",
    lastName: "Lee",
    age: 17,
    dob: new Date("2007-04-29"),
    admissionDate: new Date("2024-01-05"),
    level: 5,
    pointTotal: 315000,
    referralSource: "Juvenile Court",
    referralReason: "Multiple probation violations",
    legalStatus: "Court ordered residential treatment",
    educationInfo: "11th grade, preparing for GED",
    medicalInfo: "History of sports injuries, knee rehabilitation",
    mentalHealthInfo: "CBT therapy, excellent progress",
    peerInteraction: 5,
    adultInteraction: 5,
    investmentLevel: 5,
    dealAuthority: 5,
    hyrnaRiskLevel: "Low",
    hyrnaScore: 30,
    hyrnaAssessmentDate: new Date("2024-01-10"),
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05")
  }
];
