/**
 * Generates a plain-text youth profile template matching the Heartland Boys
 * Home Intake Form (1) — pages 1, 2 (Emergency Shelter Care), Intake Page 2,
 * and the Substance Abuse / Treatment Focus page.
 *
 * Paste the filled-out text into Add New Youth → Import tab and click
 * "Import Profile Data". The AI extracts every field below.
 */
export function generateYouthProfileTemplate(): string {
  const line = (label: string, hint = "") =>
    `${label}: ${hint ? `[${hint}]` : ""}`;

  return [
    "=============================================================",
    "  HEARTLAND BOYS HOME — INTAKE FORM TEMPLATE",
    "  Fill in values after each colon, then paste into the",
    "  Add New Youth → Import tab and click Import Profile Data.",
    "=============================================================",
    "",
    // ── PAGE 1 — INTAKE FORM (1) ──────────────────────────────────
    "INTAKE FORM (1)",
    "─────────────────────────────────────────────────────────────",
    line("Resident Name", "First Last"),
    line("Age"),
    line("Resident Address"),
    line("City"),
    line("State"),
    line("Zip"),
    line("Social Security Number"),
    line("Sex"),
    line("D.O.B.", "YYYY-MM-DD"),
    line("Admission Date", "YYYY-MM-DD"),
    line("Admission Time"),
    line("RCS in R.S."),
    line("Discharge Date", "YYYY-MM-DD"),
    line("Discharge Time"),
    line("RCS out"),
    line("Place of Birth"),
    line("Placing Agency / County"),
    line("District", "e.g. District 3J"),
    "",
    "Mother:",
    line("Mother Name"),
    line("Mother Phone"),
    "",
    "Father:",
    line("Father Name"),
    line("Father Phone"),
    "",
    line("Legal Guardian", "Name"),
    line("Guardian Relationship", "e.g. Father / Mother / Foster Parent"),
    line("Guardian Phone"),
    line("Guardian Language", "language guardian speaks"),
    "",
    line("Probation Officer"),
    line("Probation Phone"),
    line("Probation Email"),
    "",
    line("Caseworker"),
    line("Caseworker Phone"),
    line("Caseworker Email"),
    "",
    "Emergency Data:",
    line("Next of Kin Name"),
    line("Next of Kin Relationship"),
    line("Next of Kin Phone"),
    "",
    "Physical Description:",
    line("Race"),
    line("Hair Color"),
    line("Eye Color"),
    line("Height"),
    line("Weight"),
    line("Tattoos / Scars", "Yes / No — describe if Yes"),
    "",
    // ── PAGE 2 — EMERGENCY SHELTER CARE ──────────────────────────
    "EMERGENCY SHELTER CARE",
    "─────────────────────────────────────────────────────────────",
    line("Estimated Length of Stay"),
    line("Name of Placing Agency or Individual"),
    line("Date of Placement", "YYYY-MM-DD"),
    line("Time of Placement"),
    line("Reason for Emergency Placement"),
    line("Parents Notified of Placement", "Yes / No"),
    line("Immediate Needs of Child"),
    line("Intake Workers Observation of Child's Condition"),
    line("Orientation Process Completed by", "Staff name"),
    "",
    // ── INTAKE PAGE 2 — LEGAL / HEALTH / BEHAVIORS ────────────────
    "INTAKE PAGE 2",
    "─────────────────────────────────────────────────────────────",
    line("Social Worker / Caseworker / Probation Officer"),
    line("Phone"),
    line("Cell"),
    line("Email"),
    line("Guardian Ad Litem"),
    line("Guardian Ad Litem Phone"),
    line("Attorney"),
    line("Judge"),
    line("Religion"),
    "",
    "HEALTH / RELIGION / SCHOOL",
    line("Allergies"),
    line("Current Medications"),
    line("Significant Health Conditions"),
    line("Home School"),
    line("Last School Attended"),
    line("IEP", "Yes / No"),
    line("Grade"),
    "",
    "BEHAVIORS",
    line("How do you get along with others"),
    line("What are your strengths and talents"),
    line("What are your interests"),
    line("Behavior problems or significant situations to disclose"),
    line("What do you dislike about yourself"),
    line("What things make the resident angry"),
    line("Have you ever physically hurt anyone", "Yes / No"),
    line("Have you ever vandalized property", "Yes / No"),
    line("Have you ever been a member of a gang", "Yes / No"),
    line("Is there a family history of violent crimes", "Yes / No"),
    "",
    // ── SUBSTANCE ABUSE ───────────────────────────────────────────
    "SUBSTANCE ABUSE",
    "─────────────────────────────────────────────────────────────",
    line("Tobacco use in past 6-12 months", "Yes / No"),
    line("Alcohol use in past 6-12 months", "Yes / No"),
    line("Vaping / Drug / Marijuana use in past 6-12 months", "Yes / No"),
    line("Drug (UA) Testing"),
    "",
    // ── COMMUNITY RESOURCES ───────────────────────────────────────
    "COMMUNITY RESOURCES UTILIZED",
    "─────────────────────────────────────────────────────────────",
    line("Day Treatment Services", "Yes / No"),
    line("Intensive In Home Services or Home Bound Services", "Yes / No — name program if Yes"),
    line("Day School Placement (Alternative School)", "Yes / No"),
    line("1:1 School Counselor", "Yes / No — name if Yes"),
    line("Mental Health Support Services", "Yes / No"),
    line("Other Community Resources"),
    "",
    // ── DESIRED FOCUS OF TREATMENT ────────────────────────────────
    "DESIRED FOCUS OF TREATMENT",
    "─────────────────────────────────────────────────────────────",
    line("Excessive Dependency (drugs etc)", "Yes / No"),
    line("Withdrawal / Isolation", "Yes / No"),
    line("Parent / Child Relationship", "Yes / No"),
    line("Peer Relationship", "Yes / No"),
    line("Acceptance of Authority", "Yes / No"),
    line("Lying", "Yes / No"),
    line("Poor Academic Achievement", "Yes / No"),
    line("Poor Self-Esteem", "Yes / No"),
    line("Manipulative", "Yes / No"),
    line("Property Destruction", "Yes / No"),
    line("Hyperactivity", "Yes / No"),
    line("Anxiety", "Yes / No"),
    line("Verbal Aggression", "Yes / No"),
    line("Assaultive", "Yes / No"),
    line("Depression", "Yes / No"),
    line("Stealing", "Yes / No"),
    "",
    // ── DISCHARGE PLAN ────────────────────────────────────────────
    "DISCHARGE PLAN",
    "─────────────────────────────────────────────────────────────",
    line("Discharge Plan", "e.g. Go home to Dad's house in Lincoln"),
    line("Discharge Category", "e.g. Parents / Relative / Foster Care"),
    "",
    // ── MEDICAL / MENTAL HEALTH ───────────────────────────────────
    "MEDICAL",
    "─────────────────────────────────────────────────────────────",
    line("Physician"),
    line("Physician Phone"),
    line("Insurance Provider"),
    line("Policy Number"),
    line("Medical Conditions"),
    line("Medical Restrictions"),
    "",
    "MENTAL HEALTH",
    "─────────────────────────────────────────────────────────────",
    line("Current Diagnoses"),
    line("Trauma History"),
    line("Previous Treatment"),
    line("Current Counseling"),
    line("Therapist Name"),
    line("Therapist Contact"),
    line("Session Frequency", "e.g. Weekly, Bi-weekly"),
    line("Self-Harm History"),
    line("Last Incident Date", "YYYY-MM-DD"),
    line("Safety Plan", "Yes / No"),
    "",
    // ── HYRNA ─────────────────────────────────────────────────────
    "HYRNA ASSESSMENT",
    "─────────────────────────────────────────────────────────────",
    line("HYRNA Risk Level", "Low / Moderate / High"),
    line("HYRNA Score"),
    line("HYRNA Assessment Date", "YYYY-MM-DD"),
    "",
    "=============================================================",
    "  END OF TEMPLATE",
    "=============================================================",
  ].join("\n");
}

/** Triggers a browser download of the template as a .txt file. */
export function downloadYouthProfileTemplate(): void {
  const content = generateYouthProfileTemplate();
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "youth-profile-template.txt";
  a.click();
  URL.revokeObjectURL(url);
}
