// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://dnccrililqdefgxilchc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuY2NyaWxpbHFkZWZneGlsY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTY3OTIsImV4cCI6MjA2MzM3Mjc5Mn0.aryHTXq2apXroNQlEUuQ6rlg-lm_fuDeXHB2z8QJUZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
